using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace F001716
{
    public enum Failcodes
    {
        /***************    CURRENT FAILURES    ***************/
	    ER_LOW_BD_CUR                   = 1024,		//Low Board Current
	    ER_HI_BD_CUR				    = 1025,		//High Board Current
	    ER_LOW_DUT_CUR					= 1026,		//Low DUT Current
	    ER_HI_DUT_CUR					= 1027,		//High DUT Current
	    ER_LOW_FW_CUR 					= 1028,		//Low Forward Current
	    ER_HI_FW_CUR					= 1029,		//High Forward Current
	    ER_LOW_UNIT_CUR					= 1030,		//Low Unit Current
	    ER_HI_UNIT_CUR					= 1031,		//High Unit Current
	    ER_LOW_MOTOR_CUR				= 1032,		//Low Motor Current
	    ER_HI_MOTOR_CUR					= 1033,		//High Motor Current
	    ER_DUT_SHORT					= 1034,		//DUT Short
	    ER_DEAD_UNIT					= 1035,		//Dead Unit
	    ER_LOW_SLEEP_CUR				= 1036,		//Low Sleep Current
	    ER_HI_SLEEP_CUR					= 1037,		//High Sleep Current
	    ER_LOW_IDLE_CUR					= 1038,		//Low Idle Current
	    ER_HI_IDLE_CUR					= 1039,		//High Idle Current
	    ER_LOW_CONT_CUR					= 1040,		//Low Continuous Current
	    ER_HI_CONT_CUR					= 1041,		//High Continuous Current
	    ER_LOW_PEAK_CUR					= 1042,		//Low Peak Current
	    ER_HI_PEAK_CUR					= 1043,		//High Peak Current
	    ER_LOW_VLD_CUR					= 1044,		//Low VLD Current
	    ER_HI_VLD_CUR					= 1045,		//High VLD Current
	    ER_LOW_HOR1_VLD_CUR				= 1046,		//Low Horizontal 1 VLD Current
	    ER_HI_HOR1_VLD_CUR				= 1047,		//High Horizontal 1 VLD Current
	    ER_LOW_HOR2_VLD_CUR				= 1048,		//Low Horizontal 2 VLD Current
	    ER_HI_HOR2_VLD_CUR				= 1049,		//High Horizontal 2 VLD Current
	    ER_LOW_VERT_VLD_CUR				= 1050,		//Low Vertical VLD Current
	    ER_HI_VERT_VLD_CUR				= 1051,		//High Vertical VLD Current
	    ER_LOW_LEFT_VLD_CUR				= 1052,		//Low Left VLD Current
	    ER_HI_LEFT_VLD_CUR				= 1053,		//High Left VLD Current
	    ER_LOW_RIGHT_VLD_CUR			= 1054,		//Low Right VLD Current
	    ER_HI_RIGHT_VLD_CUR				= 1055,		//High Right VLD Current
	    ER_NO_PRE_FW_CUR				= 1056,		//No Pre Forward Current
	    ER_VLD_CURRENT_RISE				= 1057,		//VLD Current Rise
	    ER_LOW_LEFT_UNIT_CUR			= 1058,		//Low Left Unit Current
	    ER_HI_LEFT_UNIT_CUR				= 1059,		//High Left Unit Current
	    ER_LOW_RIGHT_UNIT_CUR			= 1060,		//Low Right Unit Current
	    ER_HI_RIGHT_UNIT_CUR			= 1061,		//High Right Unit Current
	    ER_LOW_LEFT_MTR_CUR				= 1062,		//Low Left Motor Current
	    ER_HI_LEFT_MTR_CUR				= 1063,		//High Left Motor Current
	    ER_LOW_RIGHT_MTR_CUR			= 1064,		//Low Right Motor Current
	    ER_HI_RIGHT_MTR_CUR				= 1065,		//High Right Motor Current
	    ER_LOW_FLIP_CUR					= 1066,		//Low Flipper Current
	    ER_HI_FLIP_CUR					= 1067,		//High Flipper Current
	    ER_LOW_5V_CUR					= 1068,		//Low 5V Current
	    ER_HI_5V_CUR					= 1069,		//High 5V Current
	    ER_LOW_3V_CUR					= 1070,		//Low 3V Current
	    ER_HI_3V_CUR					= 1071,		//High 3V Current
	    ER_HOR1_VLD_RISE				= 1072,		//Horizontal 1 VLD Rise
	    ER_HOR1_NO_PRE					= 1073,		//Horizontal 1 No Pre-Current
	    ER_HOR2_VLD_RISE				= 1074,		//Horizontal 2 VLD Rise
	    ER_HOR2_NO_PRE					= 1075,		//Horizontal 2 No Pre-Current
	    ER_VERT_VLD_RISE				= 1076,		//Vertical VLD Rise
	    ER_VERT_NO_PRE					= 1077,		//Vertical No Pre-Current
	    ER_LEFT_VLD_RISE				= 1078,		//Left VLD Rise
	    ER_LEFT_NO_PRE					= 1079,		//Left No Pre-Current
	    ER_RIGHT_VLD_RISE				= 1080,		//Right VLD Rise
	    ER_RIGHT_NO_PRE					= 1081,		//Right No Pre-Current
	    ER_THREE_VLD_HIGH				= 1082,		//High VLD 1, VLD 2, and VLD 3 Current
	    ER_ONE_THREE_VLD_HIGH			= 1083,		//High VLD 1 and VLD 3 Current
	    ER_ONE_TWO_VLD_HIGH				= 1084,		//High VLD 1 and VLD 2 Current
	    ER_TWO_THREE_VLD_HIGH			= 1085,		//High VLD 2 and VLD 3 Current
	    ER_LOW_ILLUM_CUR				= 1086,		//Low Illumination Current
	    ER_HI_ILLUM_CUR					= 1087,		//High Illumination Current
	    ER_LOW_STANDBY_CUR          	= 1088,     //Low Unit Standby Current
	    ER_HI_STANDBY_CUR           	= 1089,     //High Unit Standby Current	
	    ER_LOW_ACT_CUR              	= 1090,     //Low Unit Active Current
	    ER_HI_ACT_CUR               	= 1091,     //High Unit Active Current	
	    ER_BLOWN_FUSE					= 1092,		//Blown Fuse
	    ER_LOW_CHARGE_CUR				= 1093,		//Low Charge Current
	    ER_HI_CHARGE_CUR				= 1094,		//High Charge Current

        /***************    BEEPER  FAILURES    ***************/
        ER_NO_BEEP						= 1280,		//No Beep
        ER_RAZZ							= 1281,		//Razz
        ER_TRIPLE_BEEP					= 1282,		//Triple Beep Fail
        ER_RASPY_BEEP					= 1283,		//Raspy Beeper
        ER_LOW_BEEP						= 1284,		//Low Beep
        ER_BEEPER_VOLUME				= 1285,		//Beeper Volume Error
        ER_AUX_BEEPER					= 1286,		//Aux Beeper Fail
        ER_AUX_BEEPER_OFF				= 1287,		//Aux Beeper Not On

        /***************      LED FAILURES      ***************/
        ER_LED_OFF						= 1536,		//Led Off
        ER_YELLOW_OFF					= 1537,		//Yellow Led Off
        ER_RED_OFF						= 1538,		//Red Led Off
        ER_GREEN_OFF					= 1539,		//Green Led Off
        ER_BLUE_OFF						= 1540,		//Blue Led Off
        ER_WHITE_OFF					= 1541,		//White LED Off
        ER_LEFT_YELLOW_OFF				= 1542,		//Left Yellow Led Off
        ER_RIGHT_YELLOW_OFF				= 1543,		//Right Yellow Led Off
        ER_LEFT_BLUE_OFF				= 1544,		//Left Blue Led Off
        ER_RIGHT_BLUE_OFF				= 1545,		//Right Blue Led Off
        ER_AUX_LED_OFF					= 1546,		//Aux Led Off
        ER_LED_ON						= 1552,		//Led On
        ER_YELLOW_ON					= 1553,		//Yellow Led On
        ER_RED_ON						= 1554,		//Red Led On
        ER_GREEN_ON						= 1555,		//Green Led On
        ER_BLUE_ON						= 1556,		//Blue Led On
        ER_WHITE_ON						= 1557,		//White LED On
        ER_LEFT_YELLOW_ON				= 1558,		//Left Yellow Led On
        ER_RIGHT_YELLOW_ON				= 1559,		//Right Yellow Led On
        ER_BOTH_LEDS_ON					= 1560,		//Both Leds On
        ER_LEFT_BLUE_ON					= 1561,		//Left Blue On
        ER_RIGHT_BLUE_ON				= 1562,		//Right Blue On
        ER_AUX_LED_ON					= 1563,		//Aux Led On
        ER_BOTH_LEDS_FLASH				= 1568,		//Both Leds Flash
        ER_IN_STAND						= 1584,		//No Yellow Led In Stand
        ER_LAMP1						= 1585,		//Lamp One Failure
        ER_LAMP2						= 1586,		//Lamp Two Failure
        ER_LED1							= 1587,		//LED1 Failure
        ER_LED2							= 1588,		//LED2 Failure
        ER_LED3							= 1589,		//LED3 Failure
        ER_LED4							= 1590,		//LED4 Failure
        ER_LED5							= 1591,		//LED5 Failure

        /***************     SCAN  FAILURES     ***************/
        ER_BARCODE						= 1792,		//Barcode Fail
        ER_SCAN_COUNT					= 1793,		//Scan Count Fail
        ER_RECALL_DEFAULTS				= 1794,		//No Recall Defaults
        ER_LOW_SCAN_COUNT				= 1795,		//Low Scan Count
        ER_HIGH_SCAN_COUNT				= 1796,		//High Scan Count
        ER_NO_READ						= 1797,		//No Barcode Read
        ER_MIS_READ						= 1798,		//Barcode Mis Read
        ER_POOR_READ					= 1799,		//Poor Barcode Read
        ER_POOR_READ1					= 1800,		//Poor Barcode Read 1
        ER_POOR_READ2					= 1801,		//Poor Barcode Read 2
        ER_POOR_READ3					= 1802,		//Poor Barcode Read 3
        ER_POOR_READ4					= 1803,		//Poor Barcode Read 4
        ER_POOR_READ5					= 1804,		//Poor Barcode Read 5
        ER_POOR_READ6					= 1805,		//Poor Barcode Read 6
        ER_POOR_READ7					= 1806,		//Poor Barcode Read 7
        ER_POOR_READ8					= 1807,		//Poor Barcode Read 8
        ER_POOR_READ9					= 1808,		//Poor Barcode Read 9
        ER_POOR_READ10					= 1809,		//Poor Barcode Read 10
        ER_NOT_AGGRESSIVE				= 1810,		//Not Aggressive
        ER_IMAGER						= 1811,		//Imager Failure
        ER_POOR_READ_LEFT				= 1812,		//Poor Reads Left
        ER_POOR_READ_RIGHT				= 1813,		//Poor Reads Right
        ER_POOR_READ_BACK				= 1814,		//Poor Reads Back
        ER_POOR_READ_TOP				= 1815,		//Poor Reads Top
        ER_POOR_SIGNAL_FAR				= 1816,		//Poor Signal Far
        ER_POOR_SIGNAL_NEAR				= 1817,		//Poor Signal Near
        ER_SIGNAL_ERROR					= 1818,		//Barcode Signal Error
        ER_SCAN_DISABLE                 = 1819,		//Scan Disable Error
        ER_SCAN_ENABLE                  = 1820,		//Scan Enable Error
        ER_SCANRATE_LOW					= 1821,		//Scan Rate Low
        ER_SCANRATE_HIGH				= 1822,		//Scan Rate High
        ER_NO_PRE_SCANRATE				= 1823,		//No Pre Data

        /***************      COMM FAILURES      ***************/
        ER_NO_ENTER_TM					= 2048,		//No Enter Test Mode
        ER_NO_EXIT_TM					= 2049,		//No Exit Test Mode
        ER_NO_COMM						= 2050,		//No Communication
        ER_COMM_LOCK_UP					= 2051,		//Communication Lock up
        ER_OPEN_DAC_CH					= 2052,		//Failed Open Dac Channel
        ER_SET_DAC						= 2053,		//Failed To Set Dac Value
        ER_SAVE_DAC						= 2054,		//Failed To Save Dac
        ER_CLOSE_DAC_CH					= 2055,		//Failed To Close Dac Channel
        ER_DAC_BEEP						= 2056,		//Failed Dac Beep
        ER_DAC_RECALL					= 2057,		//Failed Dac Recall
        ER_INC_DAC						= 2058,		//Failed Increment Dac
        ER_DEC_DAC						= 2059,		//Failed Decrement Dac
        ER_GET_DAC						= 2060,		//Failed To Get Dac Value
        ER_DAC_TEST_CH					= 2061,		//Failed Dac Test Channel
        ER_RAM							= 2062,		//Ram Failure
        ER_NO_BOARD_FLASH				= 2063,		//No Board Flash
        ER_SERIAL_FAIL					= 2064,		//Serial Fail
        ER_SERIAL_MISMATCH				= 2065,		//Serial Mismatch
        ER_VERNON						= 2066,		//Failed Vernon
        ER_WRONG_FIRMWARE				= 2067,		//Wrong Firmware
        ER_NOVRAM_RESET					= 2068,		//Failed Novram Reset
        ER_COMM_TO						= 2069,		//Failed Communication Timeout
        ER_MENU_COMMAND					= 2070,		//Menu Command Failure
        ER_SET_TEST_STATUS				= 2071,		//Failed to Set Test Status
        ER_ENABLE_FACT_MODE				= 2072,		//Failed to Enable Factory Mode
        ER_ENABLE_LICENSE				= 2073,		//Failed to Enable License
        ER_DOWNLOAD						= 2074,		//Download Failure
        ER_CHECKSUM						= 2075,		//Checksum Failure

        /***************   INTERFACE  FAILURES   ***************/
        ER_RS232						= 2304,		//RS232 Fail
        ER_LTPN							= 2305,		//LTPN Fail
        ER_OCIA							= 2306,		//OCIA Fail
        ER_IBM							= 2307,		//IBM Fail
        ER_USB							= 2308,		//USB Fail
        ER_LASER_DATA					= 2309,		//Laser Emulation Fail
        ER_KBW							= 2310,		//KBW Fail
        ER_RTS_CTS						= 2311,		//RTS/CTS Fail
        ER_DTR							= 2312,		//DTR Fail
        ER_DSR							= 2313,		//DSR Fail
        ER_RS232_LEVEL					= 2314,		//RS232 Level Fail
        ER_USB_OPEN						= 2315,		//USB Open Fail
        ER_IBM_OPEN						= 2316,		//IBM Open Fail
        ER_KBW_LOOP						= 2317,		//KBW Loop Fail
        ER_DATA_LINE					= 2318,		//Data Line Failure
        ER_CLOCK_LINE					= 2319,		//Clock Line Failure
        ER_DISABLE						= 2320,		//Failed Disable
        ER_ENABLE						= 2321,		//Failed Enable
        ER_RESET						= 2322,		//Failed Reset
        ER_AUX							= 2323,		//Aux Fail
        ER_AUX_MISREAD					= 2324,		//Aux Misread
        ER_AUX_NO_COMM					= 2325,		//Aux No Communication
        ER_RS422						= 2326,		//RS422 Fail
        ER_WRONG_INT_BD					= 2327,		//Wrong Interface Board
        ER_WAND							= 2328,		//Wand Failure
        ER_IBM_USB						= 2329,		//IBM and USB Failure
        ER_BD_TYPE						= 2330,		//Board Type Failure
        
        /***************      IR  FAILURES      ***************/
        ER_IR							= 2560,		//IR Failure
        ER_IR_ADJUSTMENT				= 2561,		//IR Adjustment
        ER_IR_SENSITIVE					= 2562,		//IR Too Sensitive
        ER_NO_IR						= 2563,		//No IR
        ER_OUT_LONG						= 2564,		//Out Long
        ER_OUT_SHORT					= 2565,		//Out Short
        ER_IN_LONG						= 2566,		//In Long
        ER_IN_SHORT						= 2567,		//In Short
        ER_NO_DETECT					= 2568,		//No Object Detect
        ER_FAR							= 2569,		//IR Far
        ER_NEAR							= 2570,		//IR Near
        ER_IR_LOCK_UP					= 2571,		//IR Lock-up
        ER_IR_CANT_SET					= 2572,		//Can't Set IR
        ER_IR_DAC						= 2592,		//IR DAC Failure
        ER_OPEN_IR_DAC_CH				= 2593,		//Failed Open IR Dac Channel
        ER_SET_IR_DAC					= 2594,		//Failed To Set IR Dac Value
        ER_SAVE_IR_DAC					= 2595,		//Failed To Save IR Dac
        ER_CLOSE_IR_DAC_CH				= 2596,		//Failed To Close IR Dac Channel
        ER_IR_OBJECT_DETECT				= 2597,		//Failed IR Dac Object Detect
        ER_INC_IR_DAC					= 2598,		//Failed Increment IR Dac
        ER_DEC_IR_DAC					= 2599,		//Failed Decrement IR Dac
        ER_GET_IR_DAC					= 2600,		//Failed To Get IR Dac Value
        ER_AREA_DELTA					= 2601,		//Failed Area Delta
        ER_PADDLE1						= 2624,		//Failed Paddle 1
        ER_PADDLE2						= 2625,		//Failed Paddle 2
        ER_PADDLE3						= 2626,		//Failed Paddle 3
        ER_PADDLE4						= 2627,		//Failed Paddle 4

        /***************      VLD FAILURES      ***************/
        ER_NO_VLD						= 2816,		//No VLD
        ER_VLD_NOT_ON					= 2817,		//VLD Not On
        ER_VLD_NOT_OFF					= 2818,		//VLD Not Off
        ER_LOW_VLD_POWER				= 2819,		//Low VLD Power
        ER_HI_VLD_POWER					= 2820,		//High VLD Power
        ER_LOW_ON_VOLT					= 2821,		//Low VLD On Volts
        ER_HI_ON_VOLT					= 2822,		//High VLD On Volts
        ER_LOW_OFF_VOLT					= 2823,		//Low VLD Off Volts
        ER_HI_OFF_VOLT					= 2824,		//High VLD Off Volts
        ER_VLD_STATUS					= 2825,		//VLD Status Error
        ER_NO_BEAM						= 2826,		//No Beam
        ER_LOST_BEAM					= 2827,		//Lost Beam
        ER_BLOWN_VLD					= 2828,		//Blown VLD
        ER_VLD_DRIVE					= 2829,		//Failed VLD Drive Circuit
        ER_VLD_FOCUS					= 2830,		//VLD Out of Focus
        ER_DELTA_POWER					= 2831,		//Delta Power Failure
        ER_NO_HOR1_VLD					= 2832,		//No Horizontal 1 VLD
        ER_HOR1_VLD_NOT_ON				= 2833,		//Horizontal 1 VLD Not On
        ER_HOR1_VLD_NOT_OFF				= 2834,		//Horizontal 1 VLD Not Off
        ER_LOW_HOR1_VLD_POWER			= 2835,		//Horizontal 1 Low VLD Power
        ER_HI_HOR1_VLD_POWER			= 2836,		//Horizontal 1 High VLD Power
        ER_LOW_HOR1_VLD_ON_VOLT			= 2837,		//Low Horizontal 1 VLD On Volts
        ER_HI_HOR1_VLD_ON_VOLT			= 2838,		//High Horizontal 1 VLD On Volts
        ER_LOW_HOR1_VLD_OFF_VOLT 		= 2839,		//Low Horizontal 1 VLD Off Volts
        ER_HI_HOR1_VLD_OFF_VOLT			= 2840,		//High Horizontal 1 VLD Off Volts
        ER_HOR1_VLD_STATUS				= 2841,		//Horizontal 1 VLD Status Error
        ER_NO_HOR1_BEAM					= 2842,		//No Horizontal 1 Beam
        ER_LOST_HOR1_BEAM				= 2843,		//Lost Horizontal 1 Beam
        ER_BLOWN_HOR1_VOLD				= 2844,		//Blown Horizontal 1 VLD
        ER_HOR1_VLD_DRIVE				= 2845,		//Failed Horizontal 1 VLD Drive
        ER_NO_HOR2_VLD					= 2848,		//No Horizontal 2 VLD
        ER_HOR2_VLD_NOT_ON				= 2849,		//Horizontal 2 VLD Not On
        ER_HOR2_VLD_NOT_OFF				= 2850,		//Horizontal 2 VLD Not Off
        ER_LOW_HOR2_VLD_POWER			= 2851,		//Horizontal 2 Low VLD Power
        ER_HI_HOR2_VLD_POWER			= 2852,		//Horizontal 2 High VLD Power
        ER_LOW_HOR2_VLD_ON_VOLT			= 2853,		//Low Horizontal 2 VLD On Volts
        ER_HI_HOR2_VLD_ON_VOLT			= 2854,		//High Horizontal 2 VLD On Volts
        ER_LOW_HOR2_VLD_OFF_VOLT		= 2855,		//Low Horizontal 2 VLD Off Volts
        ER_HI_HOR2_VLD_OFF_VOLT			= 2856,		//High Horizontal 2 VLD Off Volts
        ER_HOR2_VLD_STATUS				= 2857,		//Horizontal 2 VLD Status Error
        ER_NO_HOR2_BEAM					= 2858,		//No Horizontal 2 Beam
        ER_LOW_HOR2_BEAM				= 2859,		//Lost Horizontal 2 Beam
        ER_BLOWN_HOR2_VLD				= 2860,		//Blown Horizontal 2 VLD
        ER_HOR2_VLD_DRIVE				= 2861,		//Failed Horizontal 2 VLD Drive
        ER_NO_VERT_VLD					= 2864,		//No Vertical VLD
        ER_VERT_VLD_NOT_ON				= 2865,		//Vertical VLD Not On
        ER_VERT_VLD_NOT_OFF				= 2866,		//Vertical VLD Not Off
        ER_LOW_VERT_VLD_POWER			= 2867,		//Low Vertical VLD Power
        ER_HI_VERT_VLD_POWER			= 2868,		//High Vertical VLD Power
        ER_LOW_VERT_VLD_ON_VOLT			= 2869,		//Low Vertical VLD On Volts
        ER_HI_VERT_VLD_ON_VOLT			= 2870,		//High Vertical VLD On Volts
        ER_LOW_VERT_VLD_OFF_VOLT		= 2871,		//Low Vertical VLD Off Volts
        ER_HI_VERT_VLD_OFF_VOLT			= 2872,		//High Vertical VLD Off Volts
        ER_VERT_VLD_STATUS				= 2873,		//Vertical VLD Status Error
        ER_NO_VERT_BEAM					= 2874,		//No Vertical Beam
        ER_LOST_VERT_BEAM				= 2875,		//Lost Vertical Beam
        ER_BLOWN_VERT_VLD				= 2876,		//Blown Vertical VLD
        ER_VERT_VLD_DRIVE				= 2877,		//Failed Vertical VLD Drive
        ER_NO_LEFT_VLD					= 2880,		//No Left VLD
        ER_LEFT_VLD_NOT_ON				= 2881,		//Left VLD Not On
        ER_LEFT_VLD_NOT_OFF				= 2882,		//Left VLD Not Off
        ER_LOW_LEFT_VLD_POWER			= 2883,		//Low Left VLD Power
        ER_HI_LEFT_VLD_POWER			= 2884,		//High Left VLD Power
        ER_LOW_LEFT_VLD_ON_VOLT			= 2885,		//Low Left VLD On Volts
        ER_HI_LEFT_VLD_ON_VOLT			= 2886,		//High Left VLD On Volts
        ER_LOW_LEFT_VLD_OFF_VOLT		= 2887,		//Low Left VLD Off Volts
        ER_HI_LEFT_VLD_OFF_VOLT			= 2888,		//High Left VLD Off Volts
        ER_LEFT_VLD_STATUS				= 2889,		//Left VLD Status Error
        ER_NO_LEFT_BEAM					= 2890,		//No Left Beam
        ER_LOST_LEFT_BEAM				= 2891,		//Lost Left Beam
        ER_BLOWN_LEFT_VLD				= 2892,		//Blown Left VLD
        ER_LEFT_VLD_DRIVE				= 2893,		//Failed Left VLD Drive
        ER_NO_RIGHT_VLD					= 2896,		//No Right VLD
        ER_RIGHT_VLD_NOT_ON				= 2897,		//Right VLD Not On
        ER_RIGHT_VLD_NOT_OFF			= 2898,		//Right VLD Not Off
        ER_LOW_RIGHT_VLD_POWER			= 2899,		//Low Right VLD Power
        ER_HI_RIGHT_VLD_POWER			= 2900,		//High Right VLD Power
        ER_LOW_RIGHT_VLD_ON_VOLT		= 2901,		//Low Right VLD On Volts
        ER_HI_RIGHT_VLD_ON_VOLT			= 2902,		//High Right VLD On Volts
        ER_LOW_RIGHT_VLD_OFF_VOLT		= 2903,		//Low Right VLD Off Volts
        ER_HI_RIGHT_VLD_OFF_VOLT		= 2904,		//High Right VLD Off Volts
        ER_RIGHT_VLD_STATUS				= 2905,		//Error Right VLD Status
        ER_NO_RIGHT_BEAM				= 2906,		//No Right Beam
        ER_LOST_RIGHT_BEAM				= 2907,		//Lost Right Beam
        ER_BLOWN_RIGHT_VLD				= 2908,		//Blown Right VLD
        ER_RIGHT_VLD_DRIVE				= 2909,		//Failed Right VLD Drive
        ER_VLD_POWER_SET				= 2912,		//Failed to Set VLD Power
        ER_TARGET						= 2913,		//Can't Target VLD
   
        /***************    FLIPPER FAILURES    ***************/
        ER_LOW_FLIPPER_FREQ				= 3072,		//Low Flipper Freq
        ER_HI_FLIPPER_FREQ				= 3073,		//High Flipper Freq
        ER_FLIPPER_NOT_ON				= 3074,		//Flipper Not On
        ER_FLIPPER_NOT_OFF				= 3075,		//Flipper Not Off
        ER_FLIPPER_LOOSE				= 3076,		//Flipper Loose
        ER_FLIPPER_HITTING				= 3077,		//Flipper Hitting
        ER_FLIPPER_BENT					= 3078,		//Flipper Bent
        ER_NO_FLIPPER					= 3079,		//No Flipper
        ER_FLIPPER_SENSITIVE			= 3080,		//Flipper Sensitive
        ER_FLIPPER_RIGHT				= 3081,		//Flipper Right
        ER_FLIPPER_LEFT					= 3082,		//Flipper Left
        ER_FLIPPER_UNSTABLE				= 3083,		//Flipper Unstable
        ER_FLIPPER_STICK				= 3084,		//Flipper Stick/Stop
        ER_FLIPPER_NOISE				= 3085,		//Flipper Noise
        ER_LOW_SPOT_SPEED				= 3086,		//Spot Speed Low
        ER_HI_SPOT_SPEED				= 3087,		//Spot Speed High
        ER_SHORT_SWEEP					= 3088,		//Short Sweep
        ER_LEFT_UNEVEN					= 3089,		//Left Uneven
        ER_RIGHT_UNEVEN					= 3090,		//Right Uneven
        ER_SLANT						= 3091,		//Slant
        ER_EXIT_ANGLE					= 3092,		//Exit Angle
        ER_ERRATIC_BEAM					= 3093,		//Erratic Beam
        ER_BROKEN_BEAM					= 3094,		//Broken Beam
        ER_DOUBLE_BEAM					= 3095,		//Double Beam
        ER_WAVY_BEAM					= 3096,		//Wavy Beam
        ER_LOW_BEAM						= 3097,		//Low Beam
        ER_HIGH_BEAM					= 3098,		//High Beam
        ER_LOW_DELTA					= 3099,		//Low Delta
        ER_HI_DELTA						= 3100,		//High Delta
        ER_LOW_FIRST_DER				= 3101,		//Low 1st Derivative
        ER_HIGH_FIRST_DER				= 3102,		//High 1st Derivative
        ER_NO_FIRST_DER					= 3103,		//No 1st Derivative
        ER_FADED_BEAM					= 3104,		//Faded Beam
        ER_LOW_BEAM_DIAM				= 3105,		//Low Beam Diameter
        ER_HI_BEAM_DIAM					= 3106,		//High Beam Diameter
        ER_LOW_LEFT_SPOT_SPEED			= 3107,		//Low Left Spot Speed
        ER_HIGH_LEFT_SPOT_SPEED			= 3108,		//High Left Spot Speed
        ER_LOW_RIGHT_SPOT_SPEED			= 3109,		//Low Right Spot Speed
        ER_HIGH_RIGHT_SPOT_SPEED		= 3110,		//High Right Spot Speed
        ER_SS_CANT_SET					= 3111,		//Cant Set Spot Speed
        ER_RESFREQ_TEST					= 3112,		//Resonance Frequency Test Failure
        ER_EXCESS_TILT                  = 3113,		//Excess Y Axis Mirror Tilt 
        
        /***************     MOTOR FAILURES     ***************/
        ER_LOW_RPM						= 3328,		//Low Motor RPM
        ER_HI_RPM						= 3329,		//High Motor RPM
        ER_NOISY_MOTOR					= 3330,		//Noisy Motor
        ER_MOTOR_VIBR					= 3331,		//Motor Vibration
        ER_MOTOR_STICK					= 3332,		//Motor Stick/Stop
        ER_BROKEN_POLYGON				= 3333,		//Broken Polygon
        ER_BAD_RASTER					= 3334,		//Bad Raster
        ER_CANT_BALANCE					= 3335,		//Can't Balance Motor
        ER_MOTOR_DRIVE					= 3336,		//Motor Drive Circuit
        ER_MOTOR_NOT_ON					= 3337,		//Motor Not On
        ER_LOW_HOR1_RPM					= 3344,		//Low Horizontal 1 Motor RPM
        ER_HI_HOR1_RPM					= 3345,		//High Horizontal 1 Motor RPM
        ER_NOISY_HOR1_MOTOR				= 3346,		//Noisy Horizontal 1 Motor
        ER_HOR1_MOTOR_VIBR				= 3347,		//Horizontal 1 Motor Vibration
        ER_HOR1_MOTOR_STICK				= 3348,		//Horizontal 1 Motor Stick/Stop
        ER_BROKEN_HOR1_POLYGON			= 3349,		//Broken Horizontal 1 Polygon
        ER_BAD_HOR1_RASTER				= 3350,		//Bad Horizontal 1 Raster
        ER_HOR1_MOTOR_DRIVE				= 3351,		//Horizontal 1 Motor Drive
        ER_HOR1_MOTOR_NOT_ON			= 3352,		//Horizontal 1 Motor Not On
        ER_LOW_HOR2_RPM					= 3360,		//Low Horizontal 2 Motor RPM
        ER_HI_HOR2_RPM					= 3361,		//High Horizontal 2 Motor RPM
        ER_NOISY_HOR2_MOTOR				= 3362,		//Noisy Horizontal 2 Motor
        ER_HOR2_MOTOR_VIBR				= 3363,		//Horizontal 2 Motor Vibration
        ER_HOR2_MOTOR_STICK				= 3364,		//Horizontal 2 Motor Stick/Stop
        ER_BROKEN_HOR2_POLYGON			= 3365,		//Broken Horizontal 2 Polygon
        ER_BAD_HOR2_RASTER				= 3366,		//Bad Horizontal 2 Raster
        ER_HOR2_MOTOR_DRIVE				= 3367,		//Horizontal 2 Motor Drive
        ER_HOR2_MOTOR_NOT_ON			= 3368,		//Horizontal 2 Motor Not On
        ER_LOW_VERT_RPM					= 3376,		//Low Vertical Motor RPM
        ER_HI_VERT_RPM					= 3377,		//High Vertical Motor RPM
        ER_NOISY_VERT_MOTOR				= 3378,		//Noisy Vertical Motor
        ER_VERT_MOTOR_VIBR				= 3379,		//Vertical Motor Vibration
        ER_VERT_MOTOR_STICK				= 3380,		//Vertical Motor Stick/Stop
        ER_BROKEN_VERT_POLYGON			= 3381,		//Broken Vertical Polygon
        ER_BAD_VERT_RASTER				= 3382,		//Bad Vertical Raster
        ER_VERT_MOTOR_DRIVE				= 3383,		//Vertical Motor Drive
        ER_VERT_MOTOR_NOT_ON			= 3384,		//Vertical Motor Not On
        ER_LOW_LEFT_RPM					= 3392,		//Low Left Motor RPM
        ER_HI_LEFT_RPM					= 3393,		//High Left Motor RPM
        ER_NOISY_LEFT_MOTOR				= 3394,		//Noisy Left Motor
        ER_LEFT_MOTOR_VIBR				= 3395,		//Left Motor Vibration
        ER_LEFT_MOTOR_STICK				= 3396,		//Left Motor Stick/Stop
        ER_BROKEN_LEFT_POLYGON			= 3397,		//Broken Left Polygon
        ER_BAD_LEFT_RASTER				= 3398,		//Bad Left Raster
        ER_LEFT_MOTOR_DRIVE				= 3399,		//Left Motor Drive Circuit
        ER_LEFT_MOTOR_NOT_ON			= 3400,		//Left Motor Not On
        ER_LOW_RIGHT_RPM				= 3408,		//Low Right Motor RPM
        ER_HI_RIGHT_RPM					= 3409,		//High Right Motor RPM
        ER_NOISY_RIGHT_MOTOR			= 3410,		//Noisy Right Motor
        ER_RIGHT_MOTOR_VIBR				= 3411,		//Motor Right Vibration
        ER_RIGHT_MOTOR_STICK			= 3412,		//Right Motor Stick/Stop
        ER_BROKEN_RIGHT_POLYGON			= 3413,		//Broken Right Polygon
        ER_BAD_RIGHT_RASTER				= 3414,		//Bad Right Raster
        ER_RIGHT_MOTOR_DRIVE			= 3415,		//Right Motor Drive Circuit
        ER_RIGHT_MOTOR_NOT_ON			= 3416,		//Right Motor Not On

        /*************** ALIGNMENT/PATTERN  FAILURES ***************/
        ER_ALIGNMENT					= 3584,		//Alignment Failure
        ER_HOR_ALIGNMENT				= 3585,		//Horizontal Alignment
        ER_VERT_ALIGNMENT				= 3586,		//Vertical Alignment
        ER_PATTERN_DISC					= 3587,		//Pattern Discrepancy
        ER_LINE_DISC					= 3588,		//Line Discrepancy
        ER_DEAD_FIELD					= 3589,		//Dead Field
        ER_SINGLE_LINE_MODE				= 3590,		//Single Line Mode
        ER_JOYSTICK						= 3591,		//Bad Joystick
        ER_AIMER_LINE_WIDTH				= 3592,		//Aimer Line Width Failure

        /***************     SCALE FAILURES     ***************/
        ER_SCALE						= 3840,		//Failed Scale
        ER_SCALE_DISPLAY				= 3841,		//Scale Display Error
        ER_SCALE_CAL					= 3842,		//Scale Calibration Error
        ER_LOAD_CELL					= 3843,		//Load Cell Error
        ER_SCALE_CONF					= 3844,		//Scale Configuration Error

        /***************   COSMETIC  FAILURES   ***************/
        ER_CASE							= 4096,		//Error Case
        ER_WINDOW						= 4097,		//Error Window
        ER_LABEL						= 4098,		//Error Label
        ER_LEDS							= 4099,		//Error Leds
        ER_FLOATERS						= 4100,		//Error Floaters
        ER_BUMPERS						= 4101,		//Error Bumpers
        ER_CABLES						= 4102,		//Error Cables
        ER_MIRRORS						= 4103,		//Error Mirrors
        ER_SHIELDS						= 4104,		//Error Shields
        ER_LENS							= 4105,		//Error Lens
        ER_POOR_PAD						= 4106,		//Poor Pad Contact
        ER_BAD_MATERIAL					= 4107,		//Bad Material
        ER_SHORT						= 4108,		//Short Circuit
        ER_OPEN							= 4109,		//Open Circuit
        ER_MISWIRE						= 4110,		//Miswire
        ER_OPEN_MISWIRE					= 4111,		//Open + Miswire
        ER_SHORT_MISWIRE				= 4112,		//Short + Miswire
        ER_OPEN_SHORT					= 4113,		//Open + Short
        ER_OPEN_SHORT_MISWIRE			= 4114,		//Open + Short + Miswire

        /***************    BUTTON  FAILURES    ***************/
        ER_PB_ALWAYS_ON					= 4352,		//Push Button Always On
        ER_PB_ALWAYS_OFF				= 4353,		//Push Button Always Off
        ER_CODEGATE_BTN_ALWAYS_ON		= 4354,		//Code Gate Button Always On
        ER_CODEGATE_BTN_ALWAYS_OFF		= 4355,		//Code Gate Button Always Off
        ER_SNGL_LINE_BTN_ALWAYS_ON		= 4356,		//Single Line Button Always On
        ER_SNGL_LINE_BTN_ALWAYS_OFF		= 4357,		//Single Line Button Always Off
        ER_ASIC_NOT_PULLED_UP			= 4358,		//ASIC Not Pulled Up
        ER_BUTTON1_ALWAYS_ON			= 4359,		//Button 1 Always On
        ER_BUTTON1_ALWAYS_OFF			= 4360,		//Button 1 Always Off
        ER_BUTTON2_ALWAYS_ON			= 4361,		//Button 2 Always On
        ER_BUTTON2_ALWAYS_OFF			= 4362,		//Button 2 Always Off
        ER_BUTTON3_ALWAYS_ON			= 4363,		//Button 3 Always On
        ER_BUTTON3_ALWAYS_OFF			= 4364,		//Button 3 Always Off
        ER_TRIGGER_ALWAYS_ON			= 4365,		//Trigger Always On
        ER_TRIGGER_ALWAYS_OFF			= 4366,		//Trigger Always Off

        /***************     MISC  FAILURES     ***************/
        ER_REED_SWITCH					= 4608,		//Reed Switch Failure
        ER_EAS_SHORT					= 4609,		//EAS Short
        ER_EAS_OPEN						= 4610,		//EAS Open
        ER_REFLECTION					= 4611,		//Reflection Fail
        ER_ILLUMINATION					= 4612,		//Illumination Failure
        ER_NO_BOARD						= 4613,		//No Board
        ER_PEAK_DATA					= 4614,		//Peak Data Error
        ER_DECAY_TIME					= 4615,		//Decay Time Error
        ER_LOW_BNDGP_REF_VOLT			= 4616,		//Bandgap Ref Voltage Low
        ER_HI_BNDGP_REF_VOLT			= 4617,		//Bandgap Ref Voltage High
        ER_LOW_THREE_VOLT				= 4618,		//3.3 Voltage High
        ER_HI_THREE_VOLT				= 4619,		//3.3 Voltage Low
        ER_TWELVE_VOLT					= 4620,		//+12 Voltage Failed
        ER_MIN_TWELVE_VOLT				= 4621,		//-12 Voltage Failed
        ER_FLASH						= 4622,		//Failed to Flash Board
        ER_VREF_LOW						= 4623,		//Low VREF Voltage
        ER_VREF_HIGH					= 4624,		//High VREF Voltage
        ER_VREF2_LOW					= 4625,		//Low VREF/2 Voltage
        ER_VREF2_HIGH					= 4626,		//High VREF/2 Voltage
        ER_ADC							= 4627,		//ADC Error
        ER_POS_THRESHOLD				= 4628,		//Positive Threshold Error
        ER_NEG_THRESHOLD				= 4629,		//Negative Threshold Error
        ER_PLUS_FIVE					= 4630,		//+5V Failure
        ER_PLUS_FIVE_RIPPLE				= 4631,		//+5V Ripple Failure
        ER_MIN_FIVE						= 4632,		//-5V Failure
        ER_TWO_SEVEN					= 4633,		//2.7V Failure
        ER_ONE_EIGHT					= 4634,		//1.8V Failure
        ER_LOW_LINE						= 4635,		//Low Line Power Up Failure
        ER_HIGH_LINE					= 4636,		//High Line Power Up Failure
        ER_LOW_FOCAL_DISTANCE			= 4637,		//Low Focal Distance
        ER_HIGH_FOCAL_DISTANCE			= 4638,		//High Focal Distance
        ER_ONE_THREE_LOW				= 4639,		//Low 1.3V Failure
        ER_ONE_THREE_HIGH				= 4640,		//High 1.3V Failure
        ER_TWO_FIVE_LOW					= 4641,		//Low 2.5V Failure
        ER_TWO_FIVE_HIGH				= 4642,		//High 2.5V Failure
        ER_POWER_UP						= 4643,		//Power Up Failure
        ER_VOLT_GEN						= 4644,		//Voltage Generated Failure
        ER_CONNECTOR					= 4645,		//Connector Continuity Failure
        ER_GROUND						= 4646,		//Ground Continuity Failure
        ER_AVG_NOISE					= 4647,		//Avg Noise Failure
        ER_PEAK_NOISE					= 4648,		//Peak Noise Failure
        ER_FIXTURE_FAILURE				= 4649,		//Fixture Failure
        ER_HALL_SWITCH_ON				= 4650,		//Hall Switch On Failure
        ER_HALL_SWITCH_OFF				= 4651,		//Hall Switch Off Failure
        ER_EAS_INTERLOCK				= 4652,		//EAS Interlock Failure
        ER_EAS_TAG_CLEAR				= 4653,		//EAS Tag Clear Failure
        ER_EAS_SENSORMATIC				= 4654,		//EAS Sensormatic Failure
        ER_CHECK_PARTS				   	= 4655,     //Supplier Issues
        ER_ONE_WIRE						= 4656,		//One Wire Failure
        ER_ONE							= 4657,		//+1.0 Volt Failure
        ER_THREE						= 4658,		//+3.0 Volt Failure
        ER_FOUR_FIVE					= 4659,		//+4.5 Volt Failure
        ER_PSOC_REV						= 4660,		//Incorrect PSOC Revision
        ER_POWER_DOWN					= 4661,		//Power Down Failure
        ER_HW_TOKEN						= 4662,		//Hardware Token Failure
        ER_LASER_NETWORK				= 4663,		//Failed to Save Laser Data to Network
        ER_ONE_FOUR_FIVE				= 4664,		//+1.45 Volt Failure
        ER_SERIAL_GEN					= 4665,		//Failed to Generate Serial Numbers
        
        /***************     FOCUS  FAILURES     ***************/
        ER_IR_GET						= 4864,		//Illumination IR Get Failure
        ER_EXPOSURE						= 4865,		//Exposure Failure
        ER_EXP_FAR						= 4866,		//Exposure Far Failure
        ER_EXP_NEAR						= 4867,		//Exposure Near Failure
        ER_EXP_LINEAR					= 4868,		//Exposure Linear Failure
        ER_CAM_TEST						= 4869,		//Camera Test Failure
        ER_ECHO_DATA					= 4870,		//Echo Data Error
        ER_ILLUM_NEAR					= 4871,		//Illumination Near Failure
        ER_ILLUM_FAR					= 4872,		//Illumination Far Failure
        ER_ILLUM_LINEAR					= 4873,		//Illumination Linear Failure
        ER_PIXEL_TEST					= 4874,		//Pixel Test Failure
        ER_28_VOLT						= 4875,		//28 Volt Failure
        ER_TOP_FAR						= 4876,		//Top Far Failure
        ER_TOP_NEAR						= 4877,		//Top Near Failure
        ER_BOTTOM_FAR					= 4878,		//Bottom Far Failure
        ER_BOTTOM_NEAR					= 4879,		//Bottom Near Failure
        ER_ILLUM_TARG					= 4880,		//Illumination Targeting Failure
        ER_ILLUM_TOP					= 4881,		//Illumination Top Failure
        ER_ILLUM_BOTTOM					= 4882,		//Illumination Bottom Failure
        ER_LOW_FREQ						= 4883,		//Low Frequency
        ER_HIGH_FREQ					= 4884,		//High Frequency
        ER_LOW_DUTY_CYCLE				= 4885,		//Low Duty Cycle
        ER_HIGH_DUTY_CYCLE				= 4886,		//High Duty Cycle
        ER_CAMERA_SPOT					= 4887,		//Camera Spot Failure
        ER_MTF							= 4888,		//MTF Failure
        ER_MEMTEST						= 4889,		//Memtest Failure
        ER_DAC1_VOLT					= 4890,		//Dac1 Voltage Failure
        ER_DAC2_VOLT					= 4891,		//Dac2 Voltage Failure
        ER_LOW_PULSE_WIDTH1				= 4892,		//Low Pulse Width 1
        ER_HI_PULSE_WIDTH1				= 4893,		//High Pulse Width 1
        ER_LOW_PULSE_WIDTH2				= 4894,		//Low Pulse Width 2
        ER_HI_PULSE_WIDTH2				= 4895,		//High Pulse Width 2
        ER_CALCULATE_CENTER				= 4896,		//Failed to Calculate Center
        ER_OFFSET_OUT					= 4897,		//Offset Out of Spec
        ER_LOW_TARG_CUR					= 4898,		//Low Target LED Current
        ER_HI_TARG_CUR					= 4899,		//High Target LED Current
        ER_PULSE_WIDTH1_RISE			= 4900,		//Pulse Width 1 Rise
        ER_PULSE_WIDTH2_RISE			= 4901,		//Pulse Width 2 Rise
        ER_ILLUM_AREA					= 4902,		//Illumination Area Failure
        ER_ILLUM_POWER					= 4903,		//Illumination Power Failure
        ER_TEST_FLEX_IMAGER_DATA		= 4904,		//Failed Test Flex Imager Data
        ER_TEST_FLEX_STRUCT_TEST		= 4905,		//Failed Test Flex Structure Test

        /***************    BLUETOOTH  FAILURES    ***************/
        ER_BT_CONNECT					= 5120,		//Bluetooth Connect Failure
        ER_DC_STEP_UP					= 5121,		//DC Step Up Failure
        ER_BATTERY_VOLT					= 5122,		//Battery Voltage Failure
        ER_FRAM							= 5123,		//Fram Error

        /***************    GPS  FAILURES    ***************/
        ER_GPS_RX_STATUS				= 5376,		//GPS Receive Status Failure
        ER_GPS_TX_POWER					= 5377,		//GPS Transmit Power Failure
        ER_GPS_TX_CURRENT				= 5378,		//GPS Transmit Current Failure
        ER_GPS_LONGITUDE				= 5379,		//GPS Longitude Failure
        ER_GPS_LATITUDE					= 5380,		//GPS Latitude Failure
        ER_GPS_CHANNEL					= 5381		//GPS Channel Number Failure
    }

    class clsFailcodes
    {
    }
}
