//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F001716 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("F001716.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string strAbort {
            get {
                return ResourceManager.GetString("strAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you hear a beep.
        /// </summary>
        internal static string strBeep {
            get {
                return ResourceManager.GetString("strBeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start to begin test.
        /// </summary>
        internal static string strBeginTest {
            get {
                return ResourceManager.GetString("strBeginTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM Rev.
        /// </summary>
        internal static string strBOMRev {
            get {
                return ResourceManager.GetString("strBOMRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string strCLEAR {
            get {
                return ResourceManager.GetString("strCLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place scanner in front of clear target.
        /// </summary>
        internal static string strClearTarget {
            get {
                return ResourceManager.GetString("strClearTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration SW Number.
        /// </summary>
        internal static string strConfigurationSW_Number {
            get {
                return ResourceManager.GetString("strConfigurationSW_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect cable to scanner.
        /// </summary>
        internal static string strConnectCableToScanner {
            get {
                return ResourceManager.GetString("strConnectCableToScanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect unit to fixture.
        /// </summary>
        internal static string strConnectUnitToFixture {
            get {
                return ResourceManager.GetString("strConnectUnitToFixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string strDescription {
            get {
                return ResourceManager.GetString("strDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TECH-ONLY DIAGNOSTICS MODE!!!.
        /// </summary>
        internal static string strDiagMode {
            get {
                return ResourceManager.GetString("strDiagMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Bag Label.
        /// </summary>
        internal static string strEnterBagLabel {
            get {
                return ResourceManager.GetString("strEnterBagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Label.
        /// </summary>
        internal static string strEnterProductLabel {
            get {
                return ResourceManager.GetString("strEnterProductLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture Error:.
        /// </summary>
        internal static string strFixtureError {
            get {
                return ResourceManager.GetString("strFixtureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Fluke Meter . . ..
        /// </summary>
        internal static string strFlukeMeter {
            get {
                return ResourceManager.GetString("strFlukeMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For 5 seconds.
        /// </summary>
        internal static string strFor5Seconds {
            get {
                return ResourceManager.GetString("strFor5Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green LEDs.
        /// </summary>
        internal static string strGreenLed {
            get {
                return ResourceManager.GetString("strGreenLed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Green Led Blink?.
        /// </summary>
        internal static string strGreenLedBlink {
            get {
                return ResourceManager.GetString("strGreenLedBlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert engine into fixture.  Select Diagnostic Test To Start..
        /// </summary>
        internal static string strInsertAndBeginDiagnostics {
            get {
                return ResourceManager.GetString("strInsertAndBeginDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert engine into fixture.  Press Start to begin test..
        /// </summary>
        internal static string strInsertAndBeginTest {
            get {
                return ResourceManager.GetString("strInsertAndBeginTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid serial number.
        /// </summary>
        internal static string strInvalidSN {
            get {
                return ResourceManager.GetString("strInvalidSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the.
        /// </summary>
        internal static string strIs_the {
            get {
                return ResourceManager.GetString("strIs_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Number.
        /// </summary>
        internal static string strItemNumber {
            get {
                return ResourceManager.GetString("strItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDCS.
        /// </summary>
        internal static string strMDCS {
            get {
                return ResourceManager.GetString("strMDCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication timeout, Please connect cable once again..
        /// </summary>
        internal static string strMessage {
            get {
                return ResourceManager.GetString("strMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Motor . . ..
        /// </summary>
        internal static string strMotor {
            get {
                return ResourceManager.GetString("strMotor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start To Initilize New Run.
        /// </summary>
        internal static string strNewRun {
            get {
                return ResourceManager.GetString("strNewRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string strNo {
            get {
                return ResourceManager.GetString("strNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string strOk {
            get {
                return ResourceManager.GetString("strOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or until message box closes.
        /// </summary>
        internal static string strOrUntilMmessageBoxCloses {
            get {
                return ResourceManager.GetString("strOrUntilMmessageBoxCloses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the MCA Number.
        /// </summary>
        internal static string strPleaseScanTheMCA_Number {
            get {
                return ResourceManager.GetString("strPleaseScanTheMCA_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the MCB Number.
        /// </summary>
        internal static string strPleaseScanTheMCB_Number {
            get {
                return ResourceManager.GetString("strPleaseScanTheMCB_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan the MCF Number.
        /// </summary>
        internal static string strPleaseScanTheMCF_Number {
            get {
                return ResourceManager.GetString("strPleaseScanTheMCF_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Agilent Power Supply . . ..
        /// </summary>
        internal static string strPowerSupply {
            get {
                return ResourceManager.GetString("strPowerSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Start to begin test.
        /// </summary>
        internal static string strPressStartToBeginTest {
            get {
                return ResourceManager.GetString("strPressStartToBeginTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press trigger switch.
        /// </summary>
        internal static string strPressTriggerSwitch {
            get {
                return ResourceManager.GetString("strPressTriggerSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Labels.
        /// </summary>
        internal static string strPrintLabels {
            get {
                return ResourceManager.GetString("strPrintLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDCS Production.
        /// </summary>
        internal static string strProductionMode {
            get {
                return ResourceManager.GetString("strProductionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt.
        /// </summary>
        internal static string strPrompt {
            get {
                return ResourceManager.GetString("strPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSOC_Rev.
        /// </summary>
        internal static string strPSOC_Rev {
            get {
                return ResourceManager.GetString("strPSOC_Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Scanner In base for bluetooth link test.
        /// </summary>
        internal static string strPutScannerInBase {
            get {
                return ResourceManager.GetString("strPutScannerInBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RED.
        /// </summary>
        internal static string strRED {
            get {
                return ResourceManager.GetString("strRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red LEDs.
        /// </summary>
        internal static string strRedLed {
            get {
                return ResourceManager.GetString("strRedLed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string strReset {
            get {
                return ResourceManager.GetString("strReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string strRetry {
            get {
                return ResourceManager.GetString("strRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please scan barcode.
        /// </summary>
        internal static string strScan {
            get {
                return ResourceManager.GetString("strScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCAN ME!.
        /// </summary>
        internal static string strSCAN_ME {
            get {
                return ResourceManager.GetString("strSCAN_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Targets.
        /// </summary>
        internal static string strScanTargets {
            get {
                return ResourceManager.GetString("strScanTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to position.
        /// </summary>
        internal static string strSetToPosition {
            get {
                return ResourceManager.GetString("strSetToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup in Progress .....
        /// </summary>
        internal static string strSetup {
            get {
                return ResourceManager.GetString("strSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN:.
        /// </summary>
        internal static string strSN {
            get {
                return ResourceManager.GetString("strSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string strStart {
            get {
                return ResourceManager.GetString("strStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string strStop {
            get {
                return ResourceManager.GetString("strStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUF Software Number.
        /// </summary>
        internal static string strSUF_SoftwareNumber {
            get {
                return ResourceManager.GetString("strSUF_SoftwareNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string strTest {
            get {
                return ResourceManager.GetString("strTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing in Progress .....
        /// </summary>
        internal static string strTesting {
            get {
                return ResourceManager.GetString("strTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MDCS Test.
        /// </summary>
        internal static string strTestMode {
            get {
                return ResourceManager.GetString("strTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string strThankYou {
            get {
                return ResourceManager.GetString("strThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string strView {
            get {
                return ResourceManager.GetString("strView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View window.
        /// </summary>
        internal static string strView_window {
            get {
                return ResourceManager.GetString("strView_window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Debug.
        /// </summary>
        internal static string strViewDebug {
            get {
                return ResourceManager.GetString("strViewDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White LEDs.
        /// </summary>
        internal static string strWhiteLed {
            get {
                return ResourceManager.GetString("strWhiteLed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string strYes {
            get {
                return ResourceManager.GetString("strYes", resourceCulture);
            }
        }
    }
}
